version: 2.1

executors:
  python:
    working_directory: ~/env-asm
    docker:
      - image: jyve/circleci-private-python-library

jobs:
  test:
    executor: python
    steps:
      - checkout
      - restore_cache:
          key: python3.6.5-v8-{{ checksum "poetry.lock" }}
      - run: make setup
      - save_cache:
          key: python3.6.5-v8-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.local
            - /home/circleci/.cache/pypoetry/virtualenvs
            - /home/circleci/.cache/pipx
      - run: make test

  lint:
    executor: python
    steps:
      - checkout
      - restore_cache:
          key: python3.6.5-v8-{{ checksum "poetry.lock" }}
      - run: make setup
      - run: make lint

  check_changelog:
    executor: python
    steps:
      - checkout
      - restore_cache:
          key: python3.6.5-v8-{{ checksum "poetry.lock" }}
      - run: make setup
      - run: make check_changelog

  deploy:
    executor: python
    steps:
      - checkout
      - run: ssh-add -D
      - run: echo "${GITHUB_JYVE_DEVOPS_PRIVATE_SSH_KEY_BASE64}" | base64 --decode | ssh-add - > /dev/null
      - restore_cache:
          key: python3.6.5-v8-{{ checksum "poetry.lock" }}
      - run: make setup
      - run: make deploy_dependencies
      - run: poetry run python devops.py deploy

workflows:
  version: 2
  on_commit:
    jobs:
      - test:
          context: private-python-library
      - lint:
          context: private-python-library
      - check_changelog:
          context: private-python-library
          filters:
            branches:
              ignore: master
      - deploy:
          context: private-python-library
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
